### ISSUE TITLE
Bug: Tumblr turns emoji back into their :code: if sent too fast

### ISSUE THREAD

**Issue by Prometheos2** [Choucroute-melba/emoji#1]
Hi! Thanks for the hard work on this add-on, it's very nice to use ^^

I noticed Tumblr DMs switched the emoji back into the :code: version when sent relatively fast. One even reverted back to :code: in the text input

Not sure what could be the root cause.

![image](https://github.com/user-attachments/assets/7a8bc183-54c7-4d09-b812-05160dfa08fe)
![firefox_bQ1aw2EvzM](https://github.com/user-attachments/assets/3e8695b8-9987-4087-b89c-ee78d535245a)

**Comment by Choucroute-melba** [comment]
Hi, thanks for taking the time to tell me.
This should be fixed in the version 2.2.1, don't hesitate to come back if it's not or if you have any othe problem 😊

**Comment by Prometheos2** [comment]
It seems to be working now. Thanks! ^^

**Comment by Prometheos2** [comment]
Hi
The same seems to be happening in Twitter/X's Direct messages
Would you like me to make a new issue or just put them all here?

**Comment by Prometheos2** [comment]
It's perfectly okay, life comes first. Thanks for maintaining this app ^^
